# Site wide configuration

title: Jeff James
description: Reader, writer, grower of artisanal beards
logo: logo.jpg # 120x120 px default image used for Twitter summary card
teaser: teaser.jpg # 400x250 px default teaser image used in image archive grid
locale:
url: http://unsquare.com

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: pygments
gems:
  - jekyll-sitemap
  - jekyll-twitter-plugin
  - jekyll-paginate
excerpt_separator: <!-- more -->
paginate: 10
paginate_path: "/blog/:num/"
collections:
  portfolio:
    output: true
    permalink: /portfolio/:categories/:title/

# Site owner
owner:
  name: Jeff James
  email: jeff@unsquare.com
  twitter: unsquare
  facebook: unsquare
  google: JeffJamesUnsquare
  bio: Reader, writer, grower of artisanal beards
  avatar: bio-photo.jpg # 160x160 px image for author byline
#disqus-shortname:

# Twitter config
twitter:
  consumer_key: 4Pt1ODJBN8BMu7nmZR6n5H5Bz
  consumer_secret: vmnHDGDYyVkqOIxIBBS5GshMtDLbqOyQ7A2xAtrufaMwP7oA3r
  access_token: 13462242-xJZL5y5e0kqvQFzm5robDx0dc6Fpg5WpxkWHigSqG
  access_token_secret: SBkluF0kN3coCzS8x97IXvu2kL2m0jnHyle4OPJdYwAGi

# Octopress config

# Default extensions
post_ext: md
page_ext: md

# Found in _templates/
post_layout: article
page_layout: article

# Format titles with titlecase?
titlecase: true

include: ['.htaccess']
exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json", "photoshop", "excludes.txt", "Rakefile"]
